spring.application.name=time
server.port = 2051
spring.datasource.url = jdbc:mysql://localhost:3306//pasaje_db
spring.datasource.username = root
spring.datasource.password = VGas1724

spring.jpa.hibernate.ddl.auto = update
spring.jpa.show-sql = true
